name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - handbuch

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Create and activate virtual environment
        run: |
          python -m venv .venv
          source .venv/bin/activate
      - name: Install dependencies
        run: |
          source .venv/bin/activate
          pip install --upgrade pip
          pip install mkdocs mkdocs-material mkdocs-glightbox mkdocs-with-pdf pymdown-extensions "markdown<3.4"
      - name: Build and deploy
        run: |
          source .venv/bin/activate
          mkdocs gh-deploy --force
