name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - handbuch # Oder dein entsprechender Branch

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies and deploy
        run: |
          pip install mkdocs mkdocs-material mkdocs-glightbox mkdocs-with-pdf pymdown-extensions
          mkdocs gh-deploy --force
